/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;

import com.balsamee.admin.*;
import com.balsamee.admin.models.*;
import com.balsamee.admin.exceptions.*;
import com.balsamee.admin.http.client.HttpClient;
import com.balsamee.admin.http.client.HttpContext;
import com.balsamee.admin.http.request.HttpRequest;
import com.balsamee.admin.http.response.HttpResponse;
import com.balsamee.admin.http.response.HttpStringResponse;
import com.balsamee.admin.http.client.APICallBack;

public class DoctorsController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static DoctorsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the DoctorsController class 
     */
    public static DoctorsController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new DoctorsController();
                }
            }
        }
        return instance;
    }

    /**
     *   Get Doctors
     *   This API by default did'nt include accepted doctor in the response  
     *     
     *   @params [Float] latitude  
     *   @params [Float] longitude  
     *   @param  [Integer] speciality_id  
     *   @param  [Integer] career_level_id  
     *   @return [JsonArray] doctors
     *  
     *   This API called if uer authenticated or not  
     *   in case of authenticated user. send required authentication headers as below:  
     *  
     *  X-Authentication-Token  
     *  X-Session-Id  
     *  
     * @param    latitude    Required parameter: Example: 
     * @param    longitude    Required parameter: Example: 
     * @param    specialityId    Required parameter: Example: 
     * @param    careerLevelId    Required parameter: Example: 
     * @param    limit    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @param    xSessionId    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getApiV5DoctorsGetAsync(
                final double latitude,
                final double longitude,
                final String specialityId,
                final String careerLevelId,
                final int limit,
                final String xAuthenticationToken,
                final String xSessionId,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/doctors");

                ///process query parameters
                Map<String, Object> _queryParameters = new HashMap<String, Object>();
                _queryParameters.put("latitude", latitude);
                _queryParameters.put("longitude", longitude);
                _queryParameters.put("speciality_id", specialityId);
                _queryParameters.put("career_level_id", careerLevelId);
                _queryParameters.put("limit", limit);
                APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("user-agent", BaseController.userAgent);


                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}