/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;

import com.balsamee.admin.*;
import com.balsamee.admin.models.*;
import com.balsamee.admin.exceptions.*;
import com.balsamee.admin.http.client.HttpClient;
import com.balsamee.admin.http.client.HttpContext;
import com.balsamee.admin.http.request.HttpRequest;
import com.balsamee.admin.http.response.HttpResponse;
import com.balsamee.admin.http.response.HttpStringResponse;
import com.balsamee.admin.http.client.APICallBack;

public class PrescriptionsController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static PrescriptionsController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the PrescriptionsController class 
     */
    public static PrescriptionsController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new PrescriptionsController();
                }
            }
        }
        return instance;
    }

    /**
     * TODO: Add Description
     * @param    xSessionId    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @param    prescriptionDate    Required parameter: Example: 
     * @param    prescriptionPrescriber    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0StartDate    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0Num    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0Duration    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0DrugId    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0Dose    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes0Notes    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794StartDate    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794Num    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794Duration    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794DrugId    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794Dose    Required parameter: Example: 
     * @param    prescriptionPresDrugsAttributes1461845708794Destroy    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void createApiV5PrescriptionsPostAsync(
                final String xSessionId,
                final String xAuthenticationToken,
                final String prescriptionDate,
                final String prescriptionPrescriber,
                final String prescriptionPresDrugsAttributes0StartDate,
                final String prescriptionPresDrugsAttributes0Num,
                final String prescriptionPresDrugsAttributes0Duration,
                final String prescriptionPresDrugsAttributes0DrugId,
                final String prescriptionPresDrugsAttributes0Dose,
                final String prescriptionPresDrugsAttributes0Notes,
                final String prescriptionPresDrugsAttributes1461845708794StartDate,
                final String prescriptionPresDrugsAttributes1461845708794Num,
                final String prescriptionPresDrugsAttributes1461845708794Duration,
                final String prescriptionPresDrugsAttributes1461845708794DrugId,
                final String prescriptionPresDrugsAttributes1461845708794Dose,
                final String prescriptionPresDrugsAttributes1461845708794Destroy,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/prescriptions");

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("user-agent", BaseController.userAgent);


                //load all fields for the outgoing API request
                Map<String, Object> _parameters = new HashMap<String, Object>();
                _parameters.put("prescription[date]", prescriptionDate);
                _parameters.put("prescription[prescriber]", prescriptionPrescriber);
                _parameters.put("prescription[pres_drugs_attributes][0][start_date]", prescriptionPresDrugsAttributes0StartDate);
                _parameters.put("prescription[pres_drugs_attributes][0][num]", prescriptionPresDrugsAttributes0Num);
                _parameters.put("prescription[pres_drugs_attributes][0][duration]", prescriptionPresDrugsAttributes0Duration);
                _parameters.put("prescription[pres_drugs_attributes][0][drug_id]", prescriptionPresDrugsAttributes0DrugId);
                _parameters.put("prescription[pres_drugs_attributes][0][dose]", prescriptionPresDrugsAttributes0Dose);
                _parameters.put("prescription[pres_drugs_attributes][0][notes]", prescriptionPresDrugsAttributes0Notes);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][start_date]", prescriptionPresDrugsAttributes1461845708794StartDate);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][num]", prescriptionPresDrugsAttributes1461845708794Num);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][duration]", prescriptionPresDrugsAttributes1461845708794Duration);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][drug_id]", prescriptionPresDrugsAttributes1461845708794DrugId);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][dose]", prescriptionPresDrugsAttributes1461845708794Dose);
                _parameters.put("prescription[pres_drugs_attributes][1461845708794][_destroy]", prescriptionPresDrugsAttributes1461845708794Destroy);

                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().post(_queryUrl, _headers, APIHelper.prepareFormFields(_parameters));

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * TODO: Add Description
     * @param    xSessionId    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getApiV5ReservationRequests4271PrescriptionsGetAsync(
                final String xSessionId,
                final String xAuthenticationToken,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/reservation_requests/4271/prescriptions");

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("user-agent", BaseController.userAgent);


                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * TODO: Add Description
     * @param    xSessionId    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getApiV5Prescriptions5a1bf82474617232620b0000GetAsync(
                final String xSessionId,
                final String xAuthenticationToken,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/prescriptions/5a1bf82474617232620b0000");

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("user-agent", BaseController.userAgent);


                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * TODO: Add Description
     * @param    xSessionId    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getApiV5ReservationRequests46464634Prescriptions5a1bf82474617232620b0000GetAsync(
                final String xSessionId,
                final String xAuthenticationToken,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/reservation_requests/46464634/prescriptions/5a1bf82474617232620b0000");

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("user-agent", BaseController.userAgent);


                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * TODO: Add Description
     * @param    xSessionId    Required parameter: Example: 
     * @param    xAuthenticationToken    Required parameter: Example: 
     * @return    Returns the void response from the API call 
     */
    public void getApiV5PrescriptionsGetAsync(
                final String xSessionId,
                final String xAuthenticationToken,
                final APICallBack<Object> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {
                //the base uri for api requests
                String _baseUri = Configuration.getBaseUri();

                //prepare query string for API call
                StringBuilder _queryBuilder = new StringBuilder("/prescriptions");

                //validate and preprocess url
                String _queryUrl = APIHelper.cleanUrl(new StringBuilder(_baseUri).append(_queryBuilder));

                //load all headers for the outgoing API request
                Map<String, String> _headers = new HashMap<String, String>();
                _headers.put("X-Session-Id", xSessionId);
                _headers.put("X-Authentication-Token", xAuthenticationToken);
                _headers.put("user-agent", BaseController.userAgent);


                //prepare and invoke the API call request to fetch the response
                final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

                //invoke the callback before request if its not null
                if (getHttpCallBack() != null)
                {
                    getHttpCallBack().OnBeforeRequest(_request);
                }

                //invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //let the caller know of the success
                            callBack.onSuccess(_context, _context);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)
                        {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}