/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AddnewchronicdiseaseRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 122273714078991377L;
    private ChronicDisease chronicDisease;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("chronic_disease")
    public ChronicDisease getChronicDisease ( ) { 
        return this.chronicDisease;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("chronic_disease")
    public void setChronicDisease (ChronicDisease value) { 
        this.chronicDisease = value;
        notifyObservers(this.chronicDisease);
    }
 
}
