/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ChronicDisease 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -8827896759538289941L;
    private String disease;
    private String comments;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("disease")
    public String getDisease ( ) { 
        return this.disease;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("disease")
    public void setDisease (String value) { 
        this.disease = value;
        notifyObservers(this.disease);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("comments")
    public String getComments ( ) { 
        return this.comments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("comments")
    public void setComments (String value) { 
        this.comments = value;
        notifyObservers(this.comments);
    }
 
}
