/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 45247650464140420L;
    private VideoExtension videoExtension;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("video_extension")
    public VideoExtension getVideoExtension ( ) { 
        return this.videoExtension;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("video_extension")
    public void setVideoExtension (VideoExtension value) { 
        this.videoExtension = value;
        notifyObservers(this.videoExtension);
    }
 
}
