/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DicomImage 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -7531345329987784003L;
    private boolean imageFlag;
    private String description;
    private String imageUploadDate;
    private String url;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("image_flag")
    public boolean getImageFlag ( ) { 
        return this.imageFlag;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("image_flag")
    public void setImageFlag (boolean value) { 
        this.imageFlag = value;
        notifyObservers(this.imageFlag);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
        notifyObservers(this.description);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("image_upload_date")
    public String getImageUploadDate ( ) { 
        return this.imageUploadDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("image_upload_date")
    public void setImageUploadDate (String value) { 
        this.imageUploadDate = value;
        notifyObservers(this.imageUploadDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
        notifyObservers(this.url);
    }
 
}
