/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class IndexlabrequestsgroupsforreservationrequestClinicvisit 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -6427643405600470844L;
    private List<String> labRequests;
    private List<LabRequestImagesGroup> labRequestImagesGroups;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_requests")
    public List<String> getLabRequests ( ) { 
        return this.labRequests;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_requests")
    public void setLabRequests (List<String> value) { 
        this.labRequests = value;
        notifyObservers(this.labRequests);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_request_images_groups")
    public List<LabRequestImagesGroup> getLabRequestImagesGroups ( ) { 
        return this.labRequestImagesGroups;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_request_images_groups")
    public void setLabRequestImagesGroups (List<LabRequestImagesGroup> value) { 
        this.labRequestImagesGroups = value;
        notifyObservers(this.labRequestImagesGroups);
    }
 
}
