/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Individual2 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 2502442402881134571L;
    private int id;
    private String birthDate;
    private String gender;
    private String bloodGroup;
    private String relationshipStatus;
    private String childrenNumber;
    private String notes;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("birth_date")
    public String getBirthDate ( ) { 
        return this.birthDate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("birth_date")
    public void setBirthDate (String value) { 
        this.birthDate = value;
        notifyObservers(this.birthDate);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("gender")
    public String getGender ( ) { 
        return this.gender;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("gender")
    public void setGender (String value) { 
        this.gender = value;
        notifyObservers(this.gender);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("blood_group")
    public String getBloodGroup ( ) { 
        return this.bloodGroup;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("blood_group")
    public void setBloodGroup (String value) { 
        this.bloodGroup = value;
        notifyObservers(this.bloodGroup);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("relationship_status")
    public String getRelationshipStatus ( ) { 
        return this.relationshipStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("relationship_status")
    public void setRelationshipStatus (String value) { 
        this.relationshipStatus = value;
        notifyObservers(this.relationshipStatus);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("children_number")
    public String getChildrenNumber ( ) { 
        return this.childrenNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("children_number")
    public void setChildrenNumber (String value) { 
        this.childrenNumber = value;
        notifyObservers(this.childrenNumber);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("notes")
    public String getNotes ( ) { 
        return this.notes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("notes")
    public void setNotes (String value) { 
        this.notes = value;
        notifyObservers(this.notes);
    }
 
}
