/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Individual3 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -4584627614320701567L;
    private int individualId;
    private String firstName;
    private String lastName;
    private String avatar;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("individual_id")
    public int getIndividualId ( ) { 
        return this.individualId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("individual_id")
    public void setIndividualId (int value) { 
        this.individualId = value;
        notifyObservers(this.individualId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("first_name")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("first_name")
    public void setFirstName (String value) { 
        this.firstName = value;
        notifyObservers(this.firstName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("last_name")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("last_name")
    public void setLastName (String value) { 
        this.lastName = value;
        notifyObservers(this.lastName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("avatar")
    public String getAvatar ( ) { 
        return this.avatar;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("avatar")
    public void setAvatar (String value) { 
        this.avatar = value;
        notifyObservers(this.avatar);
    }
 
}
