/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LabRequestImagesGroup 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -2753889901094185655L;
    private String id;
    private List<LabRequestImage> labRequestImages;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lab_request_images")
    public List<LabRequestImage> getLabRequestImages ( ) { 
        return this.labRequestImages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lab_request_images")
    public void setLabRequestImages (List<LabRequestImage> value) { 
        this.labRequestImages = value;
        notifyObservers(this.labRequestImages);
    }
 
}
