/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class NewsSource 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 7282761041577885280L;
    private String name;
    private String link;
    private String avatar;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("link")
    public String getLink ( ) { 
        return this.link;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("link")
    public void setLink (String value) { 
        this.link = value;
        notifyObservers(this.link);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("avatar")
    public String getAvatar ( ) { 
        return this.avatar;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("avatar")
    public void setAvatar (String value) { 
        this.avatar = value;
        notifyObservers(this.avatar);
    }
 
}
