/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Newssuccess 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -4418252238551960319L;
    private List<News> news;
    private Meta meta;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("news")
    public List<News> getNews ( ) { 
        return this.news;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("news")
    public void setNews (List<News> value) { 
        this.news = value;
        notifyObservers(this.news);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("meta")
    public Meta getMeta ( ) { 
        return this.meta;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("meta")
    public void setMeta (Meta value) { 
        this.meta = value;
        notifyObservers(this.meta);
    }
 
}
