/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Request 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5861985792745975015L;
    private int eventId;
    private String actionMessage;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("event_id")
    public int getEventId ( ) { 
        return this.eventId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("event_id")
    public void setEventId (int value) { 
        this.eventId = value;
        notifyObservers(this.eventId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("action_message")
    public String getActionMessage ( ) { 
        return this.actionMessage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("action_message")
    public void setActionMessage (String value) { 
        this.actionMessage = value;
        notifyObservers(this.actionMessage);
    }
 
}
