/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SpecialTag 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -2977645587926923443L;
    private String id;
    private String name;
    private String icon;
    private String color;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
        notifyObservers(this.name);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("icon")
    public String getIcon ( ) { 
        return this.icon;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("icon")
    public void setIcon (String value) { 
        this.icon = value;
        notifyObservers(this.icon);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("color")
    public String getColor ( ) { 
        return this.color;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("color")
    public void setColor (String value) { 
        this.color = value;
        notifyObservers(this.color);
    }
 
}
