/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Surgery2 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -4289486166935731463L;
    private int id;
    private String surgery;
    private String operatedOn;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
        notifyObservers(this.id);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("surgery")
    public String getSurgery ( ) { 
        return this.surgery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("surgery")
    public void setSurgery (String value) { 
        this.surgery = value;
        notifyObservers(this.surgery);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("operated_on")
    public String getOperatedOn ( ) { 
        return this.operatedOn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("operated_on")
    public void setOperatedOn (String value) { 
        this.operatedOn = value;
        notifyObservers(this.operatedOn);
    }
 
}
