/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UpdatesurgeryRequest 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 107158893168019912L;
    private Surgery surgery;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("surgery")
    public Surgery getSurgery ( ) { 
        return this.surgery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("surgery")
    public void setSurgery (Surgery value) { 
        this.surgery = value;
        notifyObservers(this.surgery);
    }
 
}
