/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class VideoExtension 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = -8517298792269335176L;
    private String status;
    private String videoRequestId;
    private int makerId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
        notifyObservers(this.status);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("video_request_id")
    public String getVideoRequestId ( ) { 
        return this.videoRequestId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("video_request_id")
    public void setVideoRequestId (String value) { 
        this.videoRequestId = value;
        notifyObservers(this.videoRequestId);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("maker_id")
    public int getMakerId ( ) { 
        return this.makerId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("maker_id")
    public void setMakerId (int value) { 
        this.makerId = value;
        notifyObservers(this.makerId);
    }
 
}
