/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin;

import com.balsamee.admin.controllers.*;
import com.balsamee.admin.http.client.HttpClient;

public class BalsameeAPIsClient {
    /**
     * Singleton access to NewsTags controller
     * @return	Returns the NewsTagsController instance 
     */
    public NewsTagsController getNewsTags() {
        return NewsTagsController.getInstance();
    }

    /**
     * Singleton access to StaticPages controller
     * @return	Returns the StaticPagesController instance 
     */
    public StaticPagesController getStaticPages() {
        return StaticPagesController.getInstance();
    }

    /**
     * Singleton access to General controller
     * @return	Returns the GeneralController instance 
     */
    public GeneralController getGeneral() {
        return GeneralController.getInstance();
    }

    /**
     * Singleton access to Misc controller
     * @return	Returns the MiscController instance 
     */
    public MiscController getMisc() {
        return MiscController.getInstance();
    }

    /**
     * Singleton access to MiniPmr controller
     * @return	Returns the MiniPmrController instance 
     */
    public MiniPmrController getMiniPmr() {
        return MiniPmrController.getInstance();
    }

    /**
     * Singleton access to ListRadiologyRequestGroups controller
     * @return	Returns the ListRadiologyRequestGroupsController instance 
     */
    public ListRadiologyRequestGroupsController getListRadiologyRequestGroups() {
        return ListRadiologyRequestGroupsController.getInstance();
    }

    /**
     * Singleton access to RadiologyRequestImageGroup controller
     * @return	Returns the RadiologyRequestImageGroupController instance 
     */
    public RadiologyRequestImageGroupController getRadiologyRequestImageGroup() {
        return RadiologyRequestImageGroupController.getInstance();
    }

    /**
     * Singleton access to Prescriptions controller
     * @return	Returns the PrescriptionsController instance 
     */
    public PrescriptionsController getPrescriptions() {
        return PrescriptionsController.getInstance();
    }

    /**
     * Singleton access to LabRequestGroups controller
     * @return	Returns the LabRequestGroupsController instance 
     */
    public LabRequestGroupsController getLabRequestGroups() {
        return LabRequestGroupsController.getInstance();
    }

    /**
     * Singleton access to PrescriptionGroups controller
     * @return	Returns the PrescriptionGroupsController instance 
     */
    public PrescriptionGroupsController getPrescriptionGroups() {
        return PrescriptionGroupsController.getInstance();
    }

    /**
     * Singleton access to LabRequestImagesGroup controller
     * @return	Returns the LabRequestImagesGroupController instance 
     */
    public LabRequestImagesGroupController getLabRequestImagesGroup() {
        return LabRequestImagesGroupController.getInstance();
    }

    /**
     * Singleton access to LabResults controller
     * @return	Returns the LabResultsController instance 
     */
    public LabResultsController getLabResults() {
        return LabResultsController.getInstance();
    }

    /**
     * Singleton access to PrescriptionImagesGroup controller
     * @return	Returns the PrescriptionImagesGroupController instance 
     */
    public PrescriptionImagesGroupController getPrescriptionImagesGroup() {
        return PrescriptionImagesGroupController.getInstance();
    }

    /**
     * Singleton access to MedicalProfile controller
     * @return	Returns the MedicalProfileController instance 
     */
    public MedicalProfileController getMedicalProfile() {
        return MedicalProfileController.getInstance();
    }

    /**
     * Singleton access to Lifestyles controller
     * @return	Returns the LifestylesController instance 
     */
    public LifestylesController getLifestyles() {
        return LifestylesController.getInstance();
    }

    /**
     * Singleton access to ChronicDiseases controller
     * @return	Returns the ChronicDiseasesController instance 
     */
    public ChronicDiseasesController getChronicDiseases() {
        return ChronicDiseasesController.getInstance();
    }

    /**
     * Singleton access to Allergies controller
     * @return	Returns the AllergiesController instance 
     */
    public AllergiesController getAllergies() {
        return AllergiesController.getInstance();
    }

    /**
     * Singleton access to IndividualImages controller
     * @return	Returns the IndividualImagesController instance 
     */
    public IndividualImagesController getIndividualImages() {
        return IndividualImagesController.getInstance();
    }

    /**
     * Singleton access to Surgeries controller
     * @return	Returns the SurgeriesController instance 
     */
    public SurgeriesController getSurgeries() {
        return SurgeriesController.getInstance();
    }

    /**
     * Singleton access to MeasurementsRevampV5 controller
     * @return	Returns the MeasurementsRevampV5Controller instance 
     */
    public MeasurementsRevampV5Controller getMeasurementsRevampV5() {
        return MeasurementsRevampV5Controller.getInstance();
    }

    /**
     * Singleton access to ReservationRequests controller
     * @return	Returns the ReservationRequestsController instance 
     */
    public ReservationRequestsController getReservationRequests() {
        return ReservationRequestsController.getInstance();
    }

    /**
     * Singleton access to NewsFeed controller
     * @return	Returns the NewsFeedController instance 
     */
    public NewsFeedController getNewsFeed() {
        return NewsFeedController.getInstance();
    }

    /**
     * Singleton access to Events controller
     * @return	Returns the EventsController instance 
     */
    public EventsController getEvents() {
        return EventsController.getInstance();
    }

    /**
     * Singleton access to NearbyLocations controller
     * @return	Returns the NearbyLocationsController instance 
     */
    public NearbyLocationsController getNearbyLocations() {
        return NearbyLocationsController.getInstance();
    }

    /**
     * Singleton access to Appointments controller
     * @return	Returns the AppointmentsController instance 
     */
    public AppointmentsController getAppointments() {
        return AppointmentsController.getInstance();
    }

    /**
     * Singleton access to Session controller
     * @return	Returns the SessionController instance 
     */
    public SessionController getSession() {
        return SessionController.getInstance();
    }

    /**
     * Singleton access to LabRequests controller
     * @return	Returns the LabRequestsController instance 
     */
    public LabRequestsController getLabRequests() {
        return LabRequestsController.getInstance();
    }

    /**
     * Singleton access to Drugs controller
     * @return	Returns the DrugsController instance 
     */
    public DrugsController getDrugs() {
        return DrugsController.getInstance();
    }

    /**
     * Singleton access to Places controller
     * @return	Returns the PlacesController instance 
     */
    public PlacesController getPlaces() {
        return PlacesController.getInstance();
    }

    /**
     * Singleton access to Doctors controller
     * @return	Returns the DoctorsController instance 
     */
    public DoctorsController getDoctors() {
        return DoctorsController.getInstance();
    }

    /**
     * Singleton access to CrossBorderTreatments controller
     * @return	Returns the CrossBorderTreatmentsController instance 
     */
    public CrossBorderTreatmentsController getCrossBorderTreatments() {
        return CrossBorderTreatmentsController.getInstance();
    }

    /**
     * Singleton access to Comments controller
     * @return	Returns the CommentsController instance 
     */
    public CommentsController getComments() {
        return CommentsController.getInstance();
    }

    /**
     * Singleton access to Paypal controller
     * @return	Returns the PaypalController instance 
     */
    public PaypalController getPaypal() {
        return PaypalController.getInstance();
    }

    /**
     * Singleton access to DicomMREs controller
     * @return	Returns the DicomMREsController instance 
     */
    public DicomMREsController getDicomMREs() {
        return DicomMREsController.getInstance();
    }

    /**
     * Singleton access to VideoRequests controller
     * @return	Returns the VideoRequestsController instance 
     */
    public VideoRequestsController getVideoRequests() {
        return VideoRequestsController.getInstance();
    }

    /**
     * Singleton access to PrescriptionImages controller
     * @return	Returns the PrescriptionImagesController instance 
     */
    public PrescriptionImagesController getPrescriptionImages() {
        return PrescriptionImagesController.getInstance();
    }

    /**
     * Singleton access to Likes controller
     * @return	Returns the LikesController instance 
     */
    public LikesController getLikes() {
        return LikesController.getInstance();
    }

    /**
     * Singleton access to VideoExtension controller
     * @return	Returns the VideoExtensionController instance 
     */
    public VideoExtensionController getVideoExtension() {
        return VideoExtensionController.getInstance();
    }

    /**
     * Singleton access to EditProfile controller
     * @return	Returns the EditProfileController instance 
     */
    public EditProfileController getEditProfile() {
        return EditProfileController.getInstance();
    }

    /**
     * Singleton access to Advertisements controller
     * @return	Returns the AdvertisementsController instance 
     */
    public AdvertisementsController getAdvertisements() {
        return AdvertisementsController.getInstance();
    }

    /**
     * Singleton access to ResetPassword controller
     * @return	Returns the ResetPasswordController instance 
     */
    public ResetPasswordController getResetPassword() {
        return ResetPasswordController.getInstance();
    }

    /**
     * Singleton access to Messages controller
     * @return	Returns the MessagesController instance 
     */
    public MessagesController getMessages() {
        return MessagesController.getInstance();
    }

    /**
     * Singleton access to LabRequestImages controller
     * @return	Returns the LabRequestImagesController instance 
     */
    public LabRequestImagesController getLabRequestImages() {
        return LabRequestImagesController.getInstance();
    }

    /**
     * Singleton access to Measurements controller
     * @return	Returns the MeasurementsController instance 
     */
    public MeasurementsController getMeasurements() {
        return MeasurementsController.getInstance();
    }

    /**
     * Singleton access to Confirmation controller
     * @return	Returns the ConfirmationController instance 
     */
    public ConfirmationController getConfirmation() {
        return ConfirmationController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public BalsameeAPIsClient() {
    }

}