/*
 * BalsameeAPIsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.balsamee.admin.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.balsamee.admin.http.client.HttpContext;
import com.balsamee.admin.models.*;

public class UnauthorizedException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = -46923273097280022L;
    private Errors errors;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("errors")
    public Errors getErrors ( ) { 
        return this.errors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("errors")
    private void setErrors (Errors value) { 
        this.errors = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public UnauthorizedException(String reason, HttpContext context) {
        super(reason, context);
    }
}
